site_name: MCS Flutter iDempiere Docs
nav:
  - Home: index.md
  - Overview: overview.md
  - Architecture: architecture.md
  - Authentication: auth-flow.md
  - API:
      - Authentication: api/authentication.md
      - News: api/news.md
      - Events: api/events.md
      - Marketplace: api/marketplace.md
      - Business Directory: api/businesses.md
      - Travel & Places: api/travel_places.md
      - Mandals: api/mandals.md
      - Search: api/search.md
  - Flutter:
      - Folder Structure: flutter/folder-structure.md
      - State Management: flutter/state-management.md
      - Models: flutter/models.md
  - Testing: testing.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md
  - Website:
      - Folder Structure: website/website-layout.md
theme:
  name: material
